### PR TITLE
now using default parameters feature of es6 for default count / options

### PR DESCRIPTION
**Pull request by shivarajnaidu**
Default params are great for optional arguments.. 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can't use it yet as I target Node.js 4. It's also not very good for options objects as it wouldn't work well with multiple options.

**Comment by shivarajnaidu** [comment]
That's fine for Node Version.. But Why **Optional Params**  are not good for Options object..?
@sindresorhus

**Comment by sindresorhus** [comment]
Say you have two options. If the users specifies one it will overwrite both. Default parameters are only assignment, they don't assign properties of an object. You could use destructuring instead, like `function test({a = "foo", b = "bar"} = {}) {`, but that's not very readable. I prefer just using Object.assign for readability. In the future we'll get native syntax for assigning object properties.

**Comment by shivarajnaidu** [comment]
ya default params are just assignment .. they would overite the param only if user didn't pass anything (or undefined ) to function.. say for example if user called the function like this.. `picrandom(['sdsdcs', 'sdccdc'])` then we can apply our default options/settings for options.. if user call `picrandom(['sdsdcs', 'sdccdc'], {count: 3})` nothing will be affected..

**Comment by sindresorhus** [comment]
Yes, that's my point. It works in this case, but if I later add another option it will not work as expected.

**Comment by shivarajnaidu** [comment]
Oh.. Okay You Are saying that user can only use one option as optional .. if we use this... Am i right.. @sindresorhus

**Comment by sindresorhus** [comment]
Yes :)

**Pull request closed without merging**
